# Generated by Django 4.2.16 on 2026-06-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "station_id",
                    models.CharField(max_length=80, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("operator", models.CharField(blank=True, max_length=200)),
                ("location_lat", models.FloatField(default=0)),
                ("location_lng", models.FloatField(default=0)),
                (
                    "station_type",
                    models.CharField(
                        choices=[
                            ("ac_level2", "AC Level 2"),
                            ("dc_fast", "DC Fast"),
                            ("swap", "Swap"),
                        ],
                        max_length=20,
                    ),
                ),
                ("num_ports", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("busy", "Busy"),
                            ("offline", "Offline"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "utilisation",
                    models.DecimalField(decimal_places=3, default=0, max_digits=4),
                ),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "stations",
            },
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "zone_id",
                    models.CharField(max_length=80, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=200)),
                ("geometry", models.TextField(default="{}")),
                ("centroid_lat", models.FloatField(blank=True, null=True)),
                ("centroid_lng", models.FloatField(blank=True, null=True)),
                (
                    "demand_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[("hot", "Hot"), ("warm", "Warm"), ("cold", "Cold")],
                        default="cold",
                        max_length=10,
                    ),
                ),
                (
                    "pop_density",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                ("poi_count", models.IntegerField(default=0)),
                (
                    "ev_traffic",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                ("station_count", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "zones",
            },
        ),
    ]
