# Generated by Django 4.2.16 on 2026-06-06 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("zones", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantedStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="New Station", max_length=200)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                (
                    "station_type",
                    models.CharField(
                        choices=[
                            ("ac_level2", "AC Level 2"),
                            ("dc_fast", "DC Fast"),
                            ("swap", "Swap"),
                        ],
                        default="dc_fast",
                        max_length=20,
                    ),
                ),
                ("num_ports", models.IntegerField(default=4)),
                ("status", models.CharField(default="planned", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planted_stations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "planted_stations",
                "ordering": ["-created_at"],
            },
        ),
    ]
