# Generated by Django 4.2.16 on 2026-06-06 14:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobilityPing',
            fields=[
                ('ping_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('speed_kmh', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('recorded_at', models.DateTimeField()),
                ('zone_id', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'mobility_pings',
                'indexes': [models.Index(fields=['recorded_at'], name='mobility_pi_recorde_48552f_idx'), models.Index(fields=['zone_id'], name='mobility_pi_zone_id_8e40db_idx')],
            },
        ),
    ]
