STUB_ZONES = [
    {
        "zone_id": "lagos_lekki_1",
        "name": "Lekki Phase 1",
        "geometry": {
            "type": "Polygon",
            "coordinates": [[[3.41, 6.42], [3.44, 6.42], [3.44, 6.44], [3.41, 6.44], [3.41, 6.42]]],
        },
        "centroid": {"lat": 6.4281, "lng": 3.4219},
        "demand_score": 87.4,
        "tier": "hot",
        "pop_density": 4200.0,
        "poi_count": 312,
        "ev_traffic": 0.78,
        "station_count": 2,
    },
    {
        "zone_id": "lagos_yaba_1",
        "name": "Yaba",
        "geometry": {
            "type": "Polygon",
            "coordinates": [[[3.36, 6.49], [3.39, 6.49], [3.39, 6.52], [3.36, 6.52], [3.36, 6.49]]],
        },
        "centroid": {"lat": 6.5059, "lng": 3.3742},
        "demand_score": 74.1,
        "tier": "hot",
        "pop_density": 6800.0,
        "poi_count": 521,
        "ev_traffic": 0.61,
        "station_count": 1,
    },
    {
        "zone_id": "lagos_ikeja_1",
        "name": "Ikeja",
        "geometry": {
            "type": "Polygon",
            "coordinates": [[[3.33, 6.58], [3.37, 6.58], [3.37, 6.62], [3.33, 6.62], [3.33, 6.58]]],
        },
        "centroid": {"lat": 6.6018, "lng": 3.3515},
        "demand_score": 61.3,
        "tier": "warm",
        "pop_density": 3900.0,
        "poi_count": 278,
        "ev_traffic": 0.44,
        "station_count": 3,
    },
]

STUB_STATIONS = [
    {
        "station_id": "sta-001",
        "name": "Lekki Phase 1 Hub",
        "operator": "Qoray Energy",
        "lat": 6.4281,
        "lng": 3.4219,
        "type": "dc_fast",
        "ports": 4,
        "status": "available",
        "utilisation": 0.45,
        "last_seen": "2025-06-06T08:00:00Z",
    },
    {
        "station_id": "sta-002",
        "name": "Yaba Tech Hub Charger",
        "operator": "NEV",
        "lat": 6.5059,
        "lng": 3.3742,
        "type": "ac_level2",
        "ports": 2,
        "status": "busy",
        "utilisation": 0.90,
        "last_seen": "2025-06-06T08:05:00Z",
    },
    {
        "station_id": "sta-003",
        "name": "Ikeja GRA Station",
        "operator": "Qoray Energy",
        "lat": 6.6018,
        "lng": 3.3515,
        "type": "dc_fast",
        "ports": 6,
        "status": "offline",
        "utilisation": 0.0,
        "last_seen": "2025-06-05T22:00:00Z",
    },
]

STUB_ROI_RESULT = {
    "location": {"lat": 6.4281, "lng": 3.4219, "name": "Lekki Phase 1"},
    "station_type": "dc_fast",
    "num_ports": 4,
    "capex_ngn": 12000000.0,
    "opex_monthly_ngn": 450000.0,
    "scenarios": {
        "conservative": {
            "daily_sessions_per_port": 7.58,
            "avg_revenue_per_session_ngn": 1800.0,
            "monthly_gross_ngn": 1641600.0,
            "monthly_net_ngn": 1191600.0,
            "payback_months": 10.07,
            "roi_12m_pct": 19.16,
        },
        "base": {
            "daily_sessions_per_port": 10.82,
            "avg_revenue_per_session_ngn": 2000.0,
            "monthly_gross_ngn": 2596800.0,
            "monthly_net_ngn": 2146800.0,
            "payback_months": 5.59,
            "roi_12m_pct": 114.68,
        },
        "optimistic": {
            "daily_sessions_per_port": 14.61,
            "avg_revenue_per_session_ngn": 2300.0,
            "monthly_gross_ngn": 4042260.0,
            "monthly_net_ngn": 3592260.0,
            "payback_months": 3.34,
            "roi_12m_pct": 258.83,
        },
    },
    "demand_score": 87.4,
    "competitor_count": 2,
    "recommendation": "Strong investment case — high demand score and low competition support fast payback under all three scenarios.",
}

STUB_BRIEF = {
    "brief_id": "00000000-0000-0000-0000-000000000001",
    "zone_id": "lagos_lekki_1",
    "generated_at": "2025-06-06T08:00:00Z",
    "headline": "Lekki Phase 1 offers a sub-12-month payback on DC fast charging with 87/100 demand.",
    "summary": "Lekki Phase 1 presents one of the highest-confidence EV charging investment opportunities in Lagos...\n\nWith a demand score of 87.4 out of 100...\n\nThe base case projects ₦2.1M monthly net revenue at full ramp.",
    "key_metrics": [
        {"label": "Demand Score", "value": "87.4 / 100"},
        {"label": "Payback Period", "value": "5.6 months"},
        {"label": "12-Month ROI", "value": "114.7%"},
        {"label": "Monthly Net (Base)", "value": "₦2,146,800"},
        {"label": "Competitor Stations", "value": "2 within 1km"},
    ],
    "risk_factors": [
        "Grid reliability in Lekki may require diesel backup capex (est. ₦1.5M additional)",
        "EV adoption curve uncertainty — projections assume 20% YoY growth",
        "Regulatory risk: DPR licensing for charging operators still evolving",
    ],
    "recommendation": "Go. The demand fundamentals are strong and payback is fast even in the conservative case. Proceed to site survey and DPR pre-application.",
}
