# Generated by Django 4.2.16 on 2026-06-06 14:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ROICache',
            fields=[
                ('cache_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('input_hash', models.CharField(max_length=64, unique=True)),
                ('result_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roi_cache',
            },
        ),
    ]
